export const SIM_VERSION = '0.0.0'

export type * from './types'
export type * from './content-types'
export { makeRng } from './rng'
export type { Rng } from './rng'
export { MAX_EXP, levelFromExp, expForLevel } from './level'
export { makeInstance, effectiveAtk, effectiveHp, isDead } from './instance'
export type { InstanceSpec } from './instance'
export { SLOT_COUNT, emptySlots, cloneTeam, cloneUnit, unitsOf, compact, front, findUnit } from './board'
export { simulate, newBattleState, MAX_ROUNDS } from './battle'
export { resolveTarget } from './targets'
export { apply, summonUnit } from './effects'
export { killUnit, dealDamage } from './faint'
export { fire, enqueueBatch, sortBatch } from './triggers'
export { drain } from './queue'
export { shopReducer, startTurn, newShopState, cloneShopState, rollShop } from './shop'
export type { ShopResult } from './shop'
export { startRun, applyAction, endTurnAndBattle, replayRun, battleSeed } from './run'
export type { RunState, TurnResult } from './run'
export * from './shopRules'
